apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-suew
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lpardo-tenant/my-app/devfile-sample-python-basic-suew@sha256:65ba8324d8c016da7ad345a1c5077738ddfad802b4634b3ef5cc94a3d82129bf
        name: my-python
        resources: {}
status: {}
